version: '3.3'

networks:
  commons-api:
    driver: bridge

services:
  api:
    build: .
    restart: always
    container_name: api
    ports:
      - "8010:8010"
    environment:
      - DB_URL=jdbc:postgresql://postgres-compose:5432/postgres?currentSchema=public
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - commons-api
    depends_on:
      - postgres-compose

  postgres-compose:
    image: postgres
    restart: always
    container_name: postgres-compose
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - commons-api

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - commons-api

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - commons-api
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost